name: Test

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_test.txt
          # Install flake8 and plugins explicitly
          pip install flake8 flake8-bugbear flake8-comprehensions
      - name: Run hassfest
        uses: home-assistant/actions/hassfest@master
      - name: Run tests
        run: |
          python -m pytest tests/ -v --tb=short --maxfail=5
      - name: Lint with flake8 (with fixed config)
        run: |
          echo "Running flake8 with proper configuration..."
          # Use the .flake8 config file we created
          python -m flake8 . --config=.flake8 --count --statistics
          echo "Flake8 linting completed successfully!"
      - name: All tests passed
        run: |
          echo "✅ All tests including linting passed!"
          echo "🎉 Integration is fully validated for Home Assistant"
