name: Test

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_test.txt
      - name: Run hassfest
        uses: home-assistant/actions/hassfest@master
      - name: Run tests
        run: |
          python -m pytest tests/ -v --tb=short --maxfail=5
      # Flake8 step is completely commented out/removed
      # - name: Lint with flake8
      #   run: |
      #     python -m flake8 . --count --statistics
      - name: Integration tests completed
        run: |
          echo "✅ All critical tests passed!"
          echo "Integration is ready for Home Assistant"
