name: "Validate"

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hassfest:
    name: "Hassfest"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4.2.2

      - name: "Run hassfest"
        uses: "home-assistant/actions/hassfest@master"

  hacs:
    name: "HACS"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4.2.2

      - name: "Run HACS validation"
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: "brands"

  tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4.2.2

      - name: "Set up Python"
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.11"

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: "Run flake8"
        run: |
          flake8 custom_components/ --config=.flake8